---
title: "Dissert-final-exp"
author: "Gabriel Robaina"
date: "2024-03-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("postgres-connect-test-script.R")
source("dissert-anova.R")

options(warn=-1)
```

# Dissert experiments

These are the experiments!

## Density plots

The following are [density plots](https://r-graph-gallery.com/density-plot) for experiments ran between 02/25/2024 and 03/20/2024.

On the first density plot, it is limited between 0 and 1. Its hiding a mode for Lambda_DD on Tier 1 that happens after 25 and 50 ms.

```{r densities, echo=FALSE}
densityMinFileAndMinIoWrite()
densityMaxFileAndMinIoWrite()
densityMaxFileAndMaxIoWrite()

densityMinFileAndMinIoRead()
densityMaxFileAndMinIoRead()
densityMaxFileAndMaxIoRead()
```

## Box plots

```{r boxplots, echo=FALSE}
boxplotMinFileAndMinIoWrite()
boxplotMaxFileAndMinIoWrite()
boxplotMaxFileAndMaxIoWrite()

boxplotMinFileAndMinIoRead()
boxplotMaxFileAndMinIoRead()
boxplotMaxFileAndMaxIoRead()
```

## ECDFs


```{r ecdfs, echo=FALSE}
ecdfMinFileAndMinIoWrite()
ecdfMaxFileAndMinIoWrite()
ecdfMaxFileAndMaxIoWrite()

ecdfMinFileAndMinIoRead()
ecdfMaxFileAndMinIoRead()
ecdfMaxFileAndMaxIoRead()
```

## Anovas

```{r anovas, echo=FALSE}
bigFileWriteAnova()
smallFileWriteAnova()

bigFileReadAnova()
smallFileReadAnova()
```